const keyboardData = {
  rows: [14, 14],

  // state
  lang: 'en',
  caps: false,
  shift: false,

  keys: [
    // row 1
    {
      code: 'Backquote',
      ru: 'ё',
      ruShift: 'Ё',
      ruCapsEffect: true,
      en: '`',
      enShift: '~',
      enCapsEffect: false,
    },
    {
      code: 'Digit1',
      ru: '1',
      ruShift: '!',
      ruCapsEffect: false,
      en: '1',
      enShift: '!',
      enCapsEffect: false,
    },
    {
      code: 'Digit2',
      ru: '2',
      ruShift: '"',
      ruCapsEffect: false,
      en: '2',
      enShift: '@',
      enCapsEffect: false,
    },
    {
      code: 'Digit3',
      ru: '3',
      ruShift: '№',
      ruCapsEffect: false,
      en: '3',
      enShift: '#',
      enCapsEffect: false,
    },
    {
      code: 'Digit4',
      ru: '4',
      ruShift: ';',
      ruCapsEffect: false,
      en: '4',
      enShift: '$',
      enCapsEffect: false,
    },
    {
      code: 'Digit5',
      ru: '5',
      ruShift: '%',
      ruCapsEffect: false,
      en: '5',
      enShift: '%',
      enCapsEffect: false,
    },
    {
      code: 'Digit6',
      ru: '6',
      ruShift: ':',
      ruCapsEffect: false,
      en: '6',
      enShift: '^',
      enCapsEffect: false,
    },
    {
      code: 'Digit7',
      ru: '7',
      ruShift: '?',
      ruCapsEffect: false,
      en: '7',
      enShift: '&',
      enCapsEffect: false,
    },
    {
      code: 'Digit8',
      ru: '8',
      ruShift: '*',
      ruCapsEffect: false,
      en: '8',
      enShift: '*',
      enCapsEffect: false,
    },
    {
      code: 'Digit9',
      ru: '9',
      ruShift: '(',
      ruCapsEffect: false,
      en: '9',
      enShift: '(',
      enCapsEffect: false,
    },
    {
      code: 'Digit0',
      ru: '0',
      ruShift: ')',
      ruCapsEffect: false,
      en: '0',
      enShift: ')',
      enCapsEffect: false,
    },
    {
      code: 'Minus',
      ru: '-',
      ruShift: '_',
      ruCapsEffect: false,
      en: '-',
      enShift: '_',
      enCapsEffect: false,
    },
    {
      code: 'Equal',
      ru: '=',
      ruShift: '+',
      ruCapsEffect: false,
      en: '=',
      enShift: '+',
      enCapsEffect: false,
    },
    {
      code: 'Backspace',
      ru: '←',
      ruShift: '←',
      ruCapsEffect: false,
      en: '←',
      enShift: '←',
      enCapsEffect: false,
      className: 'key--backspace',
    },

    // row 2
    {
      code: 'Tab',
      ru: 'tab',
      ruShift: 'tab',
      ruCapsEffect: false,
      en: 'tab',
      enShift: 'tab',
      enCapsEffect: false,
      className: 'key--tab',
    },
    {
      code: 'KeyQ',
      ru: 'й',
      ruShift: 'Й',
      ruCapsEffect: true,
      en: 'q',
      enShift: 'Q',
      enCapsEffect: true,
    },
    {
      code: 'KeyW',
      ru: 'ц',
      ruShift: 'Ц',
      ruCapsEffect: true,
      en: 'w',
      enShift: 'W',
      enCapsEffect: true,
    },
    {
      code: 'KeyE',
      ru: 'у',
      ruShift: 'У',
      ruCapsEffect: true,
      en: 'e',
      enShift: 'E',
      enCapsEffect: true,
    },
    {
      code: 'KeyR',
      ru: 'к',
      ruShift: 'К',
      ruCapsEffect: true,
      en: 'r',
      enShift: 'R',
      enCapsEffect: true,
    },
    {
      code: 'KeyT',
      ru: 'е',
      ruShift: 'Е',
      ruCapsEffect: true,
      en: 't',
      enShift: 'T',
      enCapsEffect: true,
    },
    {
      code: 'KeyY',
      ru: 'н',
      ruShift: 'Н',
      ruCapsEffect: true,
      en: 'y',
      enShift: 'Y',
      enCapsEffect: true,
    },
    {
      code: 'KeyU',
      ru: 'г',
      ruShift: 'Г',
      ruCapsEffect: true,
      en: 'u',
      enShift: 'U',
      enCapsEffect: true,
    },
    {
      code: 'KeyI',
      ru: 'ш',
      ruShift: 'Ш',
      ruCapsEffect: true,
      en: 'i',
      enShift: 'I',
      enCapsEffect: true,
    },
    {
      code: 'KeyO',
      ru: 'щ',
      ruShift: 'Щ',
      ruCapsEffect: true,
      en: 'o',
      enShift: 'O',
      enCapsEffect: true,
    },
    {
      code: 'KeyP',
      ru: 'з',
      ruShift: 'З',
      ruCapsEffect: true,
      en: 'p',
      enShift: 'P',
      enCapsEffect: true,
    },
    {
      code: 'BracketLeft',
      ru: 'х',
      ruShift: 'Х',
      ruCapsEffect: true,
      en: '[',
      enShift: '{',
      enCapsEffect: false,
    },
    {
      code: 'BracketRight',
      ru: 'ъ',
      ruShift: 'Ъ',
      ruCapsEffect: true,
      en: ']',
      enShift: '}',
      enCapsEffect: false,
    },
    {
      code: 'Backslash',
      ru: '\\',
      ruShift: '/',
      ruCapsEffect: false,
      en: '\\',
      enShift: '|',
      enCapsEffect: false,
    },
  ],
};

export default keyboardData;
