const keyboardData = {
  rows: [14, 14, 13, 12, 9],

  // state
  lang: 'en',
  caps: 'false',
  shift: 'false',

  keys: [
    // row 1
    {
      code: 'Backquote',
      ru: 'ё',
      ruShift: 'Ё',
      ruCapsEffect: true,
      en: '`',
      enShift: '~',
      enCapsEffect: false,
    },
    {
      code: 'Digit1',
      ru: '1',
      ruShift: '!',
      ruCapsEffect: false,
      en: '1',
      enShift: '!',
      enCapsEffect: false,
    },
    {
      code: 'Digit2',
      ru: '2',
      ruShift: '"',
      ruCapsEffect: false,
      en: '2',
      enShift: '@',
      enCapsEffect: false,
    },
    {
      code: 'Digit3',
      ru: '3',
      ruShift: '№',
      ruCapsEffect: false,
      en: '3',
      enShift: '#',
      enCapsEffect: false,
    },
    {
      code: 'Digit4',
      ru: '4',
      ruShift: ';',
      ruCapsEffect: false,
      en: '4',
      enShift: '$',
      enCapsEffect: false,
    },
    {
      code: 'Digit5',
      ru: '5',
      ruShift: '%',
      ruCapsEffect: false,
      en: '5',
      enShift: '%',
      enCapsEffect: false,
    },
    {
      code: 'Digit6',
      ru: '6',
      ruShift: ':',
      ruCapsEffect: false,
      en: '6',
      enShift: '^',
      enCapsEffect: false,
    },
    {
      code: 'Digit7',
      ru: '7',
      ruShift: '?',
      ruCapsEffect: false,
      en: '7',
      enShift: '&',
      enCapsEffect: false,
    },
    {
      code: 'Digit8',
      ru: '8',
      ruShift: '*',
      ruCapsEffect: false,
      en: '8',
      enShift: '*',
      enCapsEffect: false,
    },
    {
      code: 'Digit9',
      ru: '9',
      ruShift: '(',
      ruCapsEffect: false,
      en: '9',
      enShift: '(',
      enCapsEffect: false,
    },
    {
      code: 'Digit0',
      ru: '0',
      ruShift: ')',
      ruCapsEffect: false,
      en: '0',
      enShift: ')',
      enCapsEffect: false,
    },
    {
      code: 'Minus',
      ru: '-',
      ruShift: '_',
      ruCapsEffect: false,
      en: '-',
      enShift: '_',
      enCapsEffect: false,
    },
    {
      code: 'Equal',
      ru: '=',
      ruShift: '+',
      ruCapsEffect: false,
      en: '=',
      enShift: '+',
      enCapsEffect: false,
    },
    {
      code: 'Backspace',
      ru: '⇦',
      ruShift: '⇦',
      ruCapsEffect: false,
      en: '⇦',
      enShift: '⇦',
      enCapsEffect: false,
      className: 'key--backspace',
      keyModifier: true,
    },

    // row 2
    {
      code: 'Tab',
      ru: 'tab',
      ruShift: 'tab',
      ruCapsEffect: false,
      en: 'tab',
      enShift: 'tab',
      enCapsEffect: false,
      className: 'key--tab',
      keyModifier: true,
    },
    {
      code: 'KeyQ',
      ru: 'й',
      ruShift: 'Й',
      ruCapsEffect: true,
      en: 'q',
      enShift: 'Q',
      enCapsEffect: true,
    },
    {
      code: 'KeyW',
      ru: 'ц',
      ruShift: 'Ц',
      ruCapsEffect: true,
      en: 'w',
      enShift: 'W',
      enCapsEffect: true,
    },
    {
      code: 'KeyE',
      ru: 'у',
      ruShift: 'У',
      ruCapsEffect: true,
      en: 'e',
      enShift: 'E',
      enCapsEffect: true,
    },
    {
      code: 'KeyR',
      ru: 'к',
      ruShift: 'К',
      ruCapsEffect: true,
      en: 'r',
      enShift: 'R',
      enCapsEffect: true,
    },
    {
      code: 'KeyT',
      ru: 'е',
      ruShift: 'Е',
      ruCapsEffect: true,
      en: 't',
      enShift: 'T',
      enCapsEffect: true,
    },
    {
      code: 'KeyY',
      ru: 'н',
      ruShift: 'Н',
      ruCapsEffect: true,
      en: 'y',
      enShift: 'Y',
      enCapsEffect: true,
    },
    {
      code: 'KeyU',
      ru: 'г',
      ruShift: 'Г',
      ruCapsEffect: true,
      en: 'u',
      enShift: 'U',
      enCapsEffect: true,
    },
    {
      code: 'KeyI',
      ru: 'ш',
      ruShift: 'Ш',
      ruCapsEffect: true,
      en: 'i',
      enShift: 'I',
      enCapsEffect: true,
    },
    {
      code: 'KeyO',
      ru: 'щ',
      ruShift: 'Щ',
      ruCapsEffect: true,
      en: 'o',
      enShift: 'O',
      enCapsEffect: true,
    },
    {
      code: 'KeyP',
      ru: 'з',
      ruShift: 'З',
      ruCapsEffect: true,
      en: 'p',
      enShift: 'P',
      enCapsEffect: true,
    },
    {
      code: 'BracketLeft',
      ru: 'х',
      ruShift: 'Х',
      ruCapsEffect: true,
      en: '[',
      enShift: '{',
      enCapsEffect: false,
    },
    {
      code: 'BracketRight',
      ru: 'ъ',
      ruShift: 'Ъ',
      ruCapsEffect: true,
      en: ']',
      enShift: '}',
      enCapsEffect: false,
    },
    {
      code: 'Backslash',
      ru: '\\',
      ruShift: '/',
      ruCapsEffect: false,
      en: '\\',
      enShift: '|',
      enCapsEffect: false,
    },
    {
      code: 'CapsLock',
      ru: 'caps lock',
      ruShift: 'caps lock',
      ruCapsEffect: false,
      en: 'caps lock',
      enShift: 'caps lock',
      enCapsEffect: false,
      className: 'key--caps-lock',
      keyModifier: true,
    },
    {
      code: 'KeyA',
      ru: 'ф',
      ruShift: 'Ф',
      ruCapsEffect: true,
      en: 'a',
      enShift: 'A',
      enCapsEffect: true,
    },
    {
      code: 'KeyS',
      ru: 'ы',
      ruShift: 'Ы',
      ruCapsEffect: true,
      en: 's',
      enShift: 'S',
      enCapsEffect: true,
    },
    {
      code: 'KeyD',
      ru: 'в',
      ruShift: 'В',
      ruCapsEffect: true,
      en: 'd',
      enShift: 'D',
      enCapsEffect: true,
    },
    {
      code: 'KeyF',
      ru: 'а',
      ruShift: 'А',
      ruCapsEffect: true,
      en: 'f',
      enShift: 'F',
      enCapsEffect: true,
    },
    {
      code: 'KeyG',
      ru: 'п',
      ruShift: 'П',
      ruCapsEffect: true,
      en: 'g',
      enShift: 'G',
      enCapsEffect: true,
    },
    {
      code: 'KeyH',
      ru: 'р',
      ruShift: 'Р',
      ruCapsEffect: true,
      en: 'h',
      enShift: 'H',
      enCapsEffect: true,
    },
    {
      code: 'KeyJ',
      ru: 'о',
      ruShift: 'О',
      ruCapsEffect: true,
      en: 'j',
      enShift: 'J',
      enCapsEffect: true,
    },
    {
      code: 'KeyK',
      ru: 'л',
      ruShift: 'Л',
      ruCapsEffect: true,
      en: 'k',
      enShift: 'K',
      enCapsEffect: true,
    },
    {
      code: 'KeyL',
      ru: 'д',
      ruShift: 'Д',
      ruCapsEffect: true,
      en: 'l',
      enShift: 'L',
      enCapsEffect: true,
    },
    {
      code: 'Semicolon',
      ru: 'ж',
      ruShift: 'Ж',
      ruCapsEffect: true,
      en: ';',
      enShift: ':',
      enCapsEffect: false,
    },
    {
      code: 'Quote',
      ru: 'э',
      ruShift: 'Э',
      ruCapsEffect: true,
      en: '\'',
      enShift: '"',
      enCapsEffect: false,
    },
    {
      code: 'Enter',
      ru: 'enter',
      ruShift: 'enter',
      ruCapsEffect: false,
      en: 'enter',
      enShift: 'enter',
      enCapsEffect: false,
      className: 'key--enter',
      keyModifier: true,
    },
    {
      code: 'ShiftLeft',
      ru: 'shift',
      ruShift: 'shift',
      ruCapsEffect: false,
      en: 'shift',
      enShift: 'shift',
      enCapsEffect: false,
      className: 'key--shift-left',
      keyModifier: true,
    },
    {
      code: 'KeyZ',
      ru: 'я',
      ruShift: 'Я',
      ruCapsEffect: true,
      en: 'z',
      enShift: 'Z',
      enCapsEffect: true,
    },
    {
      code: 'KeyX',
      ru: 'ч',
      ruShift: 'Ч',
      ruCapsEffect: true,
      en: 'x',
      enShift: 'X',
      enCapsEffect: true,
    },
    {
      code: 'KeyC',
      ru: 'с',
      ruShift: 'С',
      ruCapsEffect: true,
      en: 'c',
      enShift: 'C',
      enCapsEffect: true,
    },
    {
      code: 'KeyV',
      ru: 'м',
      ruShift: 'М',
      ruCapsEffect: true,
      en: 'v',
      enShift: 'V',
      enCapsEffect: true,
    },
    {
      code: 'KeyB',
      ru: 'и',
      ruShift: 'И',
      ruCapsEffect: true,
      en: 'b',
      enShift: 'B',
      enCapsEffect: true,
    },
    {
      code: 'KeyN',
      ru: 'т',
      ruShift: 'Т',
      ruCapsEffect: true,
      en: 'n',
      enShift: 'N',
      enCapsEffect: true,
    },
    {
      code: 'KeyM',
      ru: 'ь',
      ruShift: 'Ь',
      ruCapsEffect: true,
      en: 'm',
      enShift: 'M',
      enCapsEffect: true,
    },
    {
      code: 'Comma',
      ru: 'б',
      ruShift: 'Б',
      ruCapsEffect: true,
      en: ',',
      enShift: '<',
      enCapsEffect: false,
    },
    {
      code: 'Period',
      ru: 'ю',
      ruShift: 'Ю',
      ruCapsEffect: true,
      en: '.',
      enShift: '>',
      enCapsEffect: false,
    },
    {
      code: 'Slash',
      ru: '.',
      ruShift: ',',
      ruCapsEffect: false,
      en: '/',
      enShift: '?',
      enCapsEffect: false,
    },
    {
      code: 'ShiftRight',
      ru: 'shift',
      ruShift: 'shift',
      ruCapsEffect: false,
      en: 'shift',
      enShift: 'shift',
      enCapsEffect: false,
      className: 'key--shift-right',
      keyModifier: true,
    },
    {
      code: 'ControlLeft',
      ru: 'ctrl',
      ruShift: 'ctrl',
      ruCapsEffect: false,
      en: 'ctrl',
      enShift: 'ctrl',
      enCapsEffect: false,
      className: 'key--ctrl-left',
      keyModifier: true,
    },
    {
      code: 'AltLeft',
      ru: 'alt',
      ruShift: 'alt',
      ruCapsEffect: false,
      en: 'alt',
      enShift: 'alt',
      enCapsEffect: false,
      className: 'key--alt-left',
      keyModifier: true,
    },
    {
      code: 'Space',
      ru: ' ',
      ruShift: ' ',
      ruCapsEffect: false,
      en: ' ',
      enShift: ' ',
      enCapsEffect: false,
      className: 'key--space',
      keyModifier: true,
    },
    {
      code: 'AltRight',
      ru: 'alt',
      ruShift: 'alt',
      ruCapsEffect: false,
      en: 'alt',
      enShift: 'alt',
      enCapsEffect: false,
      className: 'key--alt-right',
      keyModifier: true,
    },
    {
      code: 'ControlRight',
      ru: 'ctrl',
      ruShift: 'ctrl',
      ruCapsEffect: false,
      en: 'ctrl',
      enShift: 'ctrl',
      enCapsEffect: false,
      className: 'key--ctrl-right',
      keyModifier: true,
    },
    {
      code: 'ArrowLeft',
      ru: '←',
      ruShift: '←',
      ruCapsEffect: false,
      en: '←',
      enShift: '←',
      enCapsEffect: false,
      className: 'key--arrow-left',
      keyModifier: true,
    },
    {
      code: 'ArrowDown',
      ru: '↓',
      ruShift: '↓',
      ruCapsEffect: false,
      en: '↓',
      enShift: '↓',
      enCapsEffect: false,
      className: 'key--arrow-down',
      keyModifier: true,
    },
    {
      code: 'ArrowRight',
      ru: '→',
      ruShift: '→',
      ruCapsEffect: false,
      en: '→',
      enShift: '→',
      enCapsEffect: false,
      className: 'key--arrow-right',
      keyModifier: true,
    },
    {
      code: 'ArrowUp',
      ru: '↑',
      ruShift: '↑',
      ruCapsEffect: false,
      en: '↑',
      enShift: '↑',
      enCapsEffect: false,
      className: 'key--arrow-up',
      keyModifier: true,
    },
  ],
};

export default keyboardData;
